### ISSUE TITLE
能否为声笔自然加上模糊音功能 里的 前后鼻音？

### ISSUE THREAD

**Issue by awdhui** [sbsrf/home#2]
我对字的前后鼻音分不清，平翘舌倒是能区分。
最好能在候选框出现正确的完整读音方便我边打字边学习这个字怎么读，
基于此学习原因，我就不想选声笔其他系列，因为其他系列的拼音都不是完整的，但是我又想要声笔系列里的笔画筛选功能，目前没发现其他输入法同时有双拼+简拼+笔画筛选功能
![image](https://github.com/sbsrf/home/assets/99463337/fdc53293-da38-4258-84c4-e46f2cf68071)
![image](https://github.com/sbsrf/home/assets/99463337/d65ea152-7745-45ee-bafc-7477f06cae6e)
![image](https://github.com/sbsrf/home/assets/99463337/01bb4b57-4d57-4955-90fd-bd543401947e)
![image](https://github.com/sbsrf/home/assets/99463337/e23d6a6d-e0f5-4f47-967e-0fd645916665)

**Comment by sbxlmdsl** [comment]
双拼再模糊鼻音，那重码更加严重，没有什么意义了。想模糊鼻音，建议就选择声笔拼音。
